### ISSUE TITLE
shader not working?

### ISSUE THREAD

**Issue by ekidney** [balataca/aframe-transparent-video-shader#5]
hi there, just testing your glitch and it seems like the file does not want to play?

**Comment by balataca** [comment]
This seems to be a chrome related problem regarding [autoplay](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) of a video. Newer versions of chrome demand that you must have an user interaction to start playing a video, like a click. So you can add a click event listener to the whole page and when the user clicks anywhere it starts the video.

An example would be:
```
document.addEventListener('click', () => {
    video = document.querySelector('video');
    video.play();
});
```

The autoplay is currently working with firefox. If you experience any problem besides that, please feel free to fill out more details so I can reproduce your issue, such as browser version, aframe version, console logs and some screenshots.

**Comment by balataca** [comment]
I've added a better documentation on the issue.
