### ISSUE TITLE
Shader Not working with sky

### ISSUE THREAD

**Issue by manolochan** [balataca/aframe-transparent-video-shader#8]
Hi

Great work with this. It works usually fine with normal scenes but I'm wondering why it doesn't work when using a component sky as a background (ie a panorama render as an image in blender). Any ideas?

![image](https://user-images.githubusercontent.com/75830521/128184756-5bd90e44-0be5-4ebf-a264-87509bd77e58.png)

**Comment by balataca** [comment]
Thanks for reporting this bug. I've already fixed and published a new version `1.0.3` of this package. I've also updated the [demo](https://aframe-transparent-video.glitch.me/) and added a skybox.
